// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'case/case_test.dart' as case_case_test;
import 'chop/chop_test.dart' as chop_chop_test;
import 'count/count_test.dart' as count_count_test;
import 'escape/escape_html_test.dart' as escape_escape_html_test;
import 'escape/escape_regex_test.dart' as escape_escape_regex_test;
import 'split/split_test.dart' as split_split_test;
import 'stringr_test.dart' as stringr_test;
import 'util/strings_test.dart' as util_strings_test;

void main() {
  case_case_test.main();
  chop_chop_test.main();
  count_count_test.main();
  escape_escape_html_test.main();
  escape_escape_regex_test.main();
  split_split_test.main();
  stringr_test.main();
  util_strings_test.main();
}
